/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Nutri AI Food Calorie Tracker API
 * API для учёта и подсчёта калорий с возможностью ввода приёма пищи через ИИ
 * OpenAPI spec version: 1.0.0
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

export interface User {
  id: string;
  email: string;
  passwordHash: string;
  displayName?: string;
  timezone?: string;
  /** @minimum 0 */
  dailyKcalGoal?: number;
  createdAt: string;
}

export interface DayEntry {
  id: string;
  userId: string;
  date: string;
  /** @minimum 0 */
  targetKcal?: number;
  /** @minimum 0 */
  consumedKcal?: number;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  meals?: Meal[];
}

export type MealType = (typeof MealType)[keyof typeof MealType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MealType = {
  breakfast: "breakfast",
  lunch: "lunch",
  dinner: "dinner",
  snack: "snack",
  other: "other",
} as const;

export type MealSource = (typeof MealSource)[keyof typeof MealSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MealSource = {
  manual: "manual",
  ai: "ai",
} as const;

export interface Meal {
  id: string;
  dayEntryId: string;
  type: MealType;
  /** @pattern ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$ */
  time?: string;
  name?: string;
  items?: FoodItem[];
  /** @minimum 0 */
  totalKcal: number;
  source: MealSource;
  /**
   * @minimum 0
   * @maximum 1
   */
  aiConfidence?: number;
  createdAt: string;
  updatedAt: string;
}

export interface FoodItem {
  id: string;
  mealId: string;
  name: string;
  quantity: number;
  unit: string;
  /** @minimum 0 */
  kcal: number;
  protein?: number;
  fat?: number;
  carbs?: number;
  source?: string;
}

export type DietPlanMacros = {
  proteinPct?: number;
  fatPct?: number;
  carbsPct?: number;
};

export interface DietPlan {
  id: string;
  /** @nullable */
  userId?: string | null;
  name: string;
  /** @minimum 0 */
  targetKcal: number;
  macros?: DietPlanMacros;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export type AiParseLogRequestPayload = { [key: string]: unknown };

export type AiParseLogResponsePayload = { [key: string]: unknown };

export interface AiParseLog {
  id: string;
  /** @nullable */
  userId?: string | null;
  requestText: string;
  requestPayload?: AiParseLogRequestPayload;
  responsePayload?: AiParseLogResponsePayload;
  responseTimeMs?: number;
  createdAt: string;
}

export interface CalendarDay {
  date: string;
  /** @minimum 0 */
  consumedKcal: number;
  /** @minimum 0 */
  targetKcal: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  consumedPercent: number;
}

export interface SignupRequest {
  email: string;
  /** @minLength 8 */
  password: string;
  displayName?: string;
  timezone?: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface GoogleAuthRequest {
  /** Google ID token from Gmail OAuth */
  idToken: string;
}

export interface AuthResponse {
  token?: string;
  user?: User;
}

export type CreateMealRequestType =
  (typeof CreateMealRequestType)[keyof typeof CreateMealRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateMealRequestType = {
  breakfast: "breakfast",
  lunch: "lunch",
  dinner: "dinner",
  snack: "snack",
  other: "other",
} as const;

export type CreateMealRequestItemsItem = {
  name: string;
  quantity: number;
  unit: string;
  kcal: number;
  protein?: number;
  fat?: number;
  carbs?: number;
  source?: string;
};

export type CreateMealRequestSource =
  (typeof CreateMealRequestSource)[keyof typeof CreateMealRequestSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateMealRequestSource = {
  manual: "manual",
  ai: "ai",
} as const;

export interface CreateMealRequest {
  type: CreateMealRequestType;
  /** @pattern ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$ */
  time?: string;
  name?: string;
  items?: CreateMealRequestItemsItem[];
  /** @minimum 0 */
  totalKcal: number;
  source: CreateMealRequestSource;
  /**
   * @minimum 0
   * @maximum 1
   */
  aiConfidence?: number;
}

export interface AiParseMealRequest {
  userId?: string;
  date?: string;
  /** @maxLength 2048 */
  text: string;
}

export type AiParseMealResponseParsedItemsItem = {
  name?: string;
  quantity?: number;
  unit?: string;
  kcal?: number;
  protein?: number;
  fat?: number;
  carbs?: number;
  /**
   * @minimum 0
   * @maximum 1
   */
  confidence?: number;
};

export interface AiParseMealResponse {
  parsedItems?: AiParseMealResponseParsedItemsItem[];
  /** @minimum 0 */
  totalKcal?: number;
  warnings?: string[];
}

export interface StatsResponse {
  from?: string;
  to?: string;
  totalKcal?: number;
  averageKcal?: number;
  averageGoalCompletion?: number;
  days?: CalendarDay[];
}

export type ErrorDetails = { [key: string]: unknown };

export interface Error {
  error?: string;
  message?: string;
  details?: ErrorDetails;
}

/**
 * Не авторизован
 */
export type UnauthorizedResponse = Error;

/**
 * Не найдено
 */
export type NotFoundResponse = Error;

/**
 * Некорректный запрос
 */
export type BadRequestResponse = Error;

export type GetCalendarParams = {
  /**
   * @pattern ^\d{4}-\d{2}$
   */
  month: string;
};

export type GetCalendar200 = {
  month?: string;
  days?: CalendarDay[];
};

export type GetPlans200 = {
  plans?: DietPlan[];
};

export type PostPlansIdApplyParams = {
  date?: string;
};

export type PostPlansIdApply200 = {
  message?: string;
  appliedTo?: string;
};

export type GetStatsParams = {
  from: string;
  to: string;
};

/**
 * @summary Регистрация нового пользователя
 */
export const postAuthSignup = <TData = AxiosResponse<AuthResponse>>(
  signupRequest: SignupRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/auth/signup`, signupRequest, options);
};

/**
 * @summary Вход с email и паролем
 */
export const postAuthLogin = <TData = AxiosResponse<AuthResponse>>(
  loginRequest: LoginRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/auth/login`, loginRequest, options);
};

/**
 * Аутентификация через Google OAuth ID token
 * @summary Вход через Google (Gmail)
 */
export const postAuthGoogle = <TData = AxiosResponse<AuthResponse>>(
  googleAuthRequest: GoogleAuthRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/auth/google`, googleAuthRequest, options);
};

/**
 * @summary Получить календарь за месяц
 */
export const getCalendar = <TData = AxiosResponse<GetCalendar200>>(
  params: GetCalendarParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/calendar`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * @summary Получить данные за день
 */
export const getDayDate = <TData = AxiosResponse<DayEntry>>(
  date: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/day/${date}`, options);
};

/**
 * @summary Создать приём пищи
 */
export const postDayDateMeals = <TData = AxiosResponse<Meal>>(
  date: string,
  createMealRequest: CreateMealRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/day/${date}/meals`, createMealRequest, options);
};

/**
 * @summary Обновить приём пищи
 */
export const putMealsId = <TData = AxiosResponse<Meal>>(
  id: string,
  createMealRequest: CreateMealRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.put(`/meals/${id}`, createMealRequest, options);
};

/**
 * @summary Удалить приём пищи
 */
export const deleteMealsId = <TData = AxiosResponse<void>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.delete(`/meals/${id}`, options);
};

/**
 * @summary Распарсить текст через AI
 */
export const postAiParseMeal = <TData = AxiosResponse<AiParseMealResponse>>(
  aiParseMealRequest: AiParseMealRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/ai/parse-meal`, aiParseMealRequest, options);
};

/**
 * @summary Получить список планов
 */
export const getPlans = <TData = AxiosResponse<GetPlans200>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/plans`, options);
};

/**
 * @summary Применить план
 */
export const postPlansIdApply = <TData = AxiosResponse<PostPlansIdApply200>>(
  id: string,
  params?: PostPlansIdApplyParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/plans/${id}/apply`, undefined, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * @summary Статистика за период
 */
export const getStats = <TData = AxiosResponse<StatsResponse>>(
  params: GetStatsParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/stats`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export type PostAuthSignupResult = AxiosResponse<AuthResponse>;
export type PostAuthLoginResult = AxiosResponse<AuthResponse>;
export type PostAuthGoogleResult = AxiosResponse<AuthResponse>;
export type GetCalendarResult = AxiosResponse<GetCalendar200>;
export type GetDayDateResult = AxiosResponse<DayEntry>;
export type PostDayDateMealsResult = AxiosResponse<Meal>;
export type PutMealsIdResult = AxiosResponse<Meal>;
export type DeleteMealsIdResult = AxiosResponse<void>;
export type PostAiParseMealResult = AxiosResponse<AiParseMealResponse>;
export type GetPlansResult = AxiosResponse<GetPlans200>;
export type PostPlansIdApplyResult = AxiosResponse<PostPlansIdApply200>;
export type GetStatsResult = AxiosResponse<StatsResponse>;
