/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * Nutri AI Food Calorie Tracker API
 * API для учёта и подсчёта калорий с возможностью ввода приёма пищи через ИИ
 * OpenAPI spec version: 1.0.0
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

export interface User {
  id: string;
  email: string;
  passwordHash: string;
  displayName?: string;
  timezone?: string;
  /** @minimum 0 */
  dailyKcalGoal?: number;
  createdAt: string;
}

export interface DayEntry {
  id: string;
  userId: string;
  date: string;
  /** @minimum 0 */
  targetKcal?: number;
  /** @minimum 0 */
  consumedKcal?: number;
  notes?: string;
  createdAt: string;
  updatedAt: string;
  meals?: Meal[];
}

export type MealType = (typeof MealType)[keyof typeof MealType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MealType = {
  breakfast: "breakfast",
  lunch: "lunch",
  dinner: "dinner",
  snack: "snack",
  other: "other",
} as const;

export type MealSource = (typeof MealSource)[keyof typeof MealSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MealSource = {
  manual: "manual",
  ai: "ai",
} as const;

export interface Meal {
  id: string;
  dayEntryId: string;
  type: MealType;
  /** @pattern ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$ */
  time?: string;
  name?: string;
  items?: FoodItem[];
  /** @minimum 0 */
  totalKcal: number;
  source: MealSource;
  /**
   * @minimum 0
   * @maximum 1
   */
  aiConfidence?: number;
  createdAt: string;
  updatedAt: string;
}

export interface FoodItem {
  id: string;
  mealId: string;
  /**
   * Ссылка на Product
   * @nullable
   */
  productId?: string | null;
  /**
   * Ссылка на Recipe
   * @nullable
   */
  recipeId?: string | null;
  name: string;
  /** Для продукта - граммы, для рецепта - количество порций */
  quantity: number;
  unit: string;
  /** @minimum 0 */
  kcal: number;
  protein?: number;
  fat?: number;
  carbs?: number;
  /** Откуда взят item (product, recipe, ai) */
  source?: string;
}

/**
 * Источник данных
 */
export type ProductSource = (typeof ProductSource)[keyof typeof ProductSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductSource = {
  manual: "manual",
  ai: "ai",
  openfoodfacts: "openfoodfacts",
  user: "user",
} as const;

export interface Product {
  id: string;
  name: string;
  /** Нормализованное название для поиска */
  normalizedName?: string;
  kcalPer100g: number;
  proteinPer100g?: number;
  fatPer100g?: number;
  carbsPer100g?: number;
  /** @nullable */
  fiberPer100g?: number | null;
  /** @nullable */
  sugarPer100g?: number | null;
  /** Источник данных */
  source?: ProductSource;
  /** Проверенный продукт */
  isVerified?: boolean;
  /** Сколько раз использовали */
  usageCount?: number;
  /**
   * ID пользователя, если создал пользователь
   * @nullable
   */
  createdBy?: string | null;
  /**
   * EAN/UPC штрихкод
   * @nullable
   */
  barcode?: string | null;
  /** @nullable */
  brand?: string | null;
  /** @nullable */
  category?: string | null;
  createdAt: string;
  updatedAt?: string;
}

export type RecipeCategory =
  (typeof RecipeCategory)[keyof typeof RecipeCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RecipeCategory = {
  breakfast: "breakfast",
  lunch: "lunch",
  dinner: "dinner",
  snack: "snack",
  dessert: "dessert",
  drink: "drink",
  other: "other",
} as const;

export interface Recipe {
  id: string;
  userId: string;
  name: string;
  description?: string;
  /**
   * Количество порций в рецепте
   * @minimum 1
   */
  servings: number;
  category?: RecipeCategory;
  ingredients?: RecipeIngredient[];
  /** @minimum 0 */
  totalKcal?: number;
  totalProtein?: number;
  totalFat?: number;
  totalCarbs?: number;
  kcalPerServing?: number;
  proteinPerServing?: number;
  fatPerServing?: number;
  carbsPerServing?: number;
  /** @nullable */
  imageUrl?: string | null;
  /**
   * Время приготовления в минутах
   * @nullable
   */
  cookingTime?: number | null;
  /** Сколько раз использовали */
  usageCount?: number;
  /** @nullable */
  lastUsedAt?: string | null;
  /** Поделиться с другими пользователями */
  isPublic?: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface RecipeIngredient {
  id?: string;
  recipeId?: string;
  /** Ссылка на Product */
  productId: string;
  /** Закэшированное название для быстрого отображения */
  productName?: string;
  quantity: number;
  unit: string;
  kcal?: number;
  protein?: number;
  fat?: number;
  carbs?: number;
  /** @nullable */
  notes?: string | null;
}

export type DietPlanMacros = {
  proteinPct?: number;
  fatPct?: number;
  carbsPct?: number;
};

export interface DietPlan {
  id: string;
  /** @nullable */
  userId?: string | null;
  name: string;
  /** @minimum 0 */
  targetKcal: number;
  macros?: DietPlanMacros;
  description?: string;
  createdAt: string;
  updatedAt: string;
}

export type AiParseLogRequestPayload = { [key: string]: unknown };

export type AiParseLogResponsePayload = { [key: string]: unknown };

export interface AiParseLog {
  id: string;
  /** @nullable */
  userId?: string | null;
  requestText: string;
  requestPayload?: AiParseLogRequestPayload;
  responsePayload?: AiParseLogResponsePayload;
  responseTimeMs?: number;
  createdAt: string;
}

export interface CalendarDay {
  date: string;
  /** @minimum 0 */
  consumedKcal: number;
  /** @minimum 0 */
  targetKcal: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  consumedPercent: number;
}

export interface SignupRequest {
  email: string;
  /** @minLength 8 */
  password: string;
  displayName?: string;
  timezone?: string;
}

export interface LoginRequest {
  email: string;
  password: string;
  timezone?: string;
}

export interface GoogleAuthRequest {
  /** Google ID token from Gmail OAuth */
  idToken: string;
  timezone?: string;
}

export interface AuthResponse {
  token?: string;
  user?: User;
}

export type CreateMealRequestType =
  (typeof CreateMealRequestType)[keyof typeof CreateMealRequestType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateMealRequestType = {
  breakfast: "breakfast",
  lunch: "lunch",
  dinner: "dinner",
  snack: "snack",
  other: "other",
} as const;

export type CreateMealRequestItemsItem = {
  productId?: string;
  recipeId?: string;
  name: string;
  quantity: number;
  unit: string;
  kcal: number;
  protein?: number;
  fat?: number;
  carbs?: number;
};

export type CreateMealRequestSource =
  (typeof CreateMealRequestSource)[keyof typeof CreateMealRequestSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateMealRequestSource = {
  manual: "manual",
  ai: "ai",
} as const;

export interface CreateMealRequest {
  type: CreateMealRequestType;
  /** @pattern ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$ */
  time?: string;
  name?: string;
  items?: CreateMealRequestItemsItem[];
  /** @minimum 0 */
  totalKcal: number;
  source: CreateMealRequestSource;
  aiConfidence?: number;
}

export type CreateProductRequestSource =
  (typeof CreateProductRequestSource)[keyof typeof CreateProductRequestSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProductRequestSource = {
  manual: "manual",
  ai: "ai",
  openfoodfacts: "openfoodfacts",
} as const;

export interface CreateProductRequest {
  name: string;
  kcalPer100g: number;
  proteinPer100g?: number;
  fatPer100g?: number;
  carbsPer100g?: number;
  fiberPer100g?: number;
  sugarPer100g?: number;
  barcode?: string;
  brand?: string;
  category?: string;
  source?: CreateProductRequestSource;
}

export interface UpdateProductRequest {
  name?: string;
  kcalPer100g?: number;
  proteinPer100g?: number;
  fatPer100g?: number;
  carbsPer100g?: number;
  fiberPer100g?: number;
  sugarPer100g?: number;
  barcode?: string;
  brand?: string;
  category?: string;
}

export type CreateRecipeRequestCategory =
  (typeof CreateRecipeRequestCategory)[keyof typeof CreateRecipeRequestCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRecipeRequestCategory = {
  breakfast: "breakfast",
  lunch: "lunch",
  dinner: "dinner",
  snack: "snack",
  dessert: "dessert",
  drink: "drink",
  other: "other",
} as const;

export type CreateRecipeRequestIngredientsItem = {
  productId: string;
  quantity: number;
  unit: string;
  notes?: string;
};

export interface CreateRecipeRequest {
  name: string;
  description?: string;
  /** @minimum 1 */
  servings: number;
  category?: CreateRecipeRequestCategory;
  ingredients: CreateRecipeRequestIngredientsItem[];
  cookingTime?: number;
  imageUrl?: string;
  isPublic?: boolean;
}

export type UpdateRecipeRequestIngredientsItem = {
  productId?: string;
  quantity?: number;
  unit?: string;
  notes?: string;
};

export interface UpdateRecipeRequest {
  name?: string;
  description?: string;
  /** @minimum 1 */
  servings?: number;
  category?: string;
  ingredients?: UpdateRecipeRequestIngredientsItem[];
  cookingTime?: number;
  imageUrl?: string;
  isPublic?: boolean;
}

export type AddRecipeToMealRequestMealType =
  (typeof AddRecipeToMealRequestMealType)[keyof typeof AddRecipeToMealRequestMealType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AddRecipeToMealRequestMealType = {
  breakfast: "breakfast",
  lunch: "lunch",
  dinner: "dinner",
  snack: "snack",
  other: "other",
} as const;

export interface AddRecipeToMealRequest {
  date: string;
  mealType: AddRecipeToMealRequestMealType;
  /** Количество порций (можно дробное) */
  servings: number;
  /** @pattern ^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$ */
  time?: string;
}

export interface AiParseMealRequest {
  text: string;
}

export type AiParseMealResponseParsedType =
  (typeof AiParseMealResponseParsedType)[keyof typeof AiParseMealResponseParsedType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AiParseMealResponseParsedType = {
  breakfast: "breakfast",
  lunch: "lunch",
  dinner: "dinner",
  snack: "snack",
  other: "other",
} as const;

export type AiParseMealResponseParsedItemsItemProductSuggestionsItem = {
  productId?: string;
  name?: string;
  kcalPer100g?: number;
  source?: string;
  matchScore?: number;
};

export type AiParseMealResponseParsedItemsItemRecipeSuggestionsItem = {
  recipeId?: string;
  name?: string;
  kcalPerServing?: number;
  servings?: number;
  usageCount?: number;
  matchScore?: number;
};

/**
 * @nullable
 */
export type AiParseMealResponseParsedItemsItemAiFallback = {
  name?: string;
  kcalPer100g?: number;
  proteinPer100g?: number;
  fatPer100g?: number;
  carbsPer100g?: number;
  confidence?: number;
} | null;

export type AiParseMealResponseParsedItemsItem = {
  rawText?: string;
  parsedName?: string;
  quantity?: number;
  unit?: string;
  productSuggestions?: AiParseMealResponseParsedItemsItemProductSuggestionsItem[];
  recipeSuggestions?: AiParseMealResponseParsedItemsItemRecipeSuggestionsItem[];
  /** @nullable */
  aiFallback?: AiParseMealResponseParsedItemsItemAiFallback;
};

export type AiParseMealResponseParsed = {
  type?: AiParseMealResponseParsedType;
  items?: AiParseMealResponseParsedItemsItem[];
};

export interface AiParseMealResponse {
  parsed?: AiParseMealResponseParsed;
  /** Список items с низким confidence */
  needsReview?: string[];
}

export type StatsResponsePeriod = {
  from?: string;
  to?: string;
};

export type StatsResponseAverageMacros = {
  protein?: number;
  fat?: number;
  carbs?: number;
};

export interface StatsResponse {
  period?: StatsResponsePeriod;
  averageKcal?: number;
  totalKcal?: number;
  daysTracked?: number;
  averageMacros?: StatsResponseAverageMacros;
}

export type ErrorDetails = { [key: string]: unknown };

export interface Error {
  error?: string;
  message?: string;
  details?: ErrorDetails;
}

/**
 * Некорректные данные
 */
export type BadRequestResponse = Error;

/**
 * Требуется авторизация
 */
export type UnauthorizedResponse = Error;

/**
 * Ресурс не найден
 */
export type NotFoundResponse = Error;

export type GetCalendarParams = {
  /**
   * @pattern ^\d{4}-\d{2}$
   */
  month: string;
};

export type GetCalendar200 = {
  month?: string;
  days?: CalendarDay[];
};

export type GetProductsParams = {
  /**
   * Поиск по названию
   */
  search?: string;
  category?: string;
  source?: GetProductsSource;
  limit?: number;
  offset?: number;
};

export type GetProductsSource =
  (typeof GetProductsSource)[keyof typeof GetProductsSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetProductsSource = {
  manual: "manual",
  ai: "ai",
  openfoodfacts: "openfoodfacts",
  user: "user",
} as const;

export type GetProducts200 = {
  products?: Product[];
  total?: number;
};

export type GetProductsSearchParams = {
  q: string;
  limit?: number;
};

export type GetProductsSearch200 = {
  products?: Product[];
};

export type GetRecipesParams = {
  category?: GetRecipesCategory;
  /**
   * Поиск по названию
   */
  search?: string;
  sort?: GetRecipesSort;
  limit?: number;
  offset?: number;
};

export type GetRecipesCategory =
  (typeof GetRecipesCategory)[keyof typeof GetRecipesCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRecipesCategory = {
  breakfast: "breakfast",
  lunch: "lunch",
  dinner: "dinner",
  snack: "snack",
  dessert: "dessert",
  drink: "drink",
  other: "other",
} as const;

export type GetRecipesSort =
  (typeof GetRecipesSort)[keyof typeof GetRecipesSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetRecipesSort = {
  recent: "recent",
  popular: "popular",
  name: "name",
} as const;

export type GetRecipes200 = {
  recipes?: Recipe[];
  total?: number;
};

export type GetRecipesPublicParams = {
  search?: string;
  category?: string;
  /**
   * Фильтр по калориям на порцию
   */
  maxKcal?: number;
  limit?: number;
};

export type GetRecipesPublic200 = {
  recipes?: Recipe[];
};

export type GetPlans200 = {
  plans?: DietPlan[];
};

export type PostPlansIdApplyParams = {
  date?: string;
};

export type PostPlansIdApply200 = {
  message?: string;
  appliedTo?: string;
};

export type GetStatsParams = {
  from: string;
  to: string;
};

/**
 * @summary Регистрация нового пользователя
 */
export const postAuthSignup = <TData = AxiosResponse<AuthResponse>>(
  signupRequest: SignupRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/auth/signup`, signupRequest, options);
};

/**
 * @summary Вход с email и паролем
 */
export const postAuthLogin = <TData = AxiosResponse<AuthResponse>>(
  loginRequest: LoginRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/auth/login`, loginRequest, options);
};

/**
 * Аутентификация через Google OAuth ID token
 * @summary Вход через Google (Gmail)
 */
export const postAuthGoogle = <TData = AxiosResponse<AuthResponse>>(
  googleAuthRequest: GoogleAuthRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/auth/google`, googleAuthRequest, options);
};

/**
 * @summary Получить календарь за месяц
 */
export const getCalendar = <TData = AxiosResponse<GetCalendar200>>(
  params: GetCalendarParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/calendar`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * @summary Получить данные за день
 */
export const getDayDate = <TData = AxiosResponse<DayEntry>>(
  date: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/day/${date}`, options);
};

/**
 * @summary Создать приём пищи
 */
export const postDayDateMeals = <TData = AxiosResponse<Meal>>(
  date: string,
  createMealRequest: CreateMealRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/day/${date}/meals`, createMealRequest, options);
};

/**
 * @summary Обновить приём пищи
 */
export const putMealsId = <TData = AxiosResponse<Meal>>(
  id: string,
  createMealRequest: CreateMealRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.put(`/meals/${id}`, createMealRequest, options);
};

/**
 * @summary Удалить приём пищи
 */
export const deleteMealsId = <TData = AxiosResponse<void>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.delete(`/meals/${id}`, options);
};

/**
 * @summary Распарсить текст через AI
 */
export const postAiParseMeal = <TData = AxiosResponse<AiParseMealResponse>>(
  aiParseMealRequest: AiParseMealRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/ai/parse-meal`, aiParseMealRequest, options);
};

/**
 * @summary Получить список продуктов
 */
export const getProducts = <TData = AxiosResponse<GetProducts200>>(
  params?: GetProductsParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/products`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * @summary Создать новый продукт
 */
export const postProducts = <TData = AxiosResponse<Product>>(
  createProductRequest: CreateProductRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/products`, createProductRequest, options);
};

/**
 * @summary Поиск продуктов (для автокомплита)
 */
export const getProductsSearch = <TData = AxiosResponse<GetProductsSearch200>>(
  params: GetProductsSearchParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/products/search`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * @summary Получить продукт по ID
 */
export const getProductsId = <TData = AxiosResponse<Product>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/products/${id}`, options);
};

/**
 * @summary Обновить продукт
 */
export const putProductsId = <TData = AxiosResponse<Product>>(
  id: string,
  updateProductRequest: UpdateProductRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.put(`/products/${id}`, updateProductRequest, options);
};

/**
 * @summary Удалить продукт
 */
export const deleteProductsId = <TData = AxiosResponse<void>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.delete(`/products/${id}`, options);
};

/**
 * @summary Поиск продукта по штрихкоду
 */
export const getProductsBarcodeBarcode = <TData = AxiosResponse<Product>>(
  barcode: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/products/barcode/${barcode}`, options);
};

/**
 * @summary Получить список рецептов пользователя
 */
export const getRecipes = <TData = AxiosResponse<GetRecipes200>>(
  params?: GetRecipesParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/recipes`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * @summary Создать новый рецепт
 */
export const postRecipes = <TData = AxiosResponse<Recipe>>(
  createRecipeRequest: CreateRecipeRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/recipes`, createRecipeRequest, options);
};

/**
 * @summary Получить рецепт
 */
export const getRecipesId = <TData = AxiosResponse<Recipe>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/recipes/${id}`, options);
};

/**
 * @summary Обновить рецепт
 */
export const putRecipesId = <TData = AxiosResponse<Recipe>>(
  id: string,
  updateRecipeRequest: UpdateRecipeRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.put(`/recipes/${id}`, updateRecipeRequest, options);
};

/**
 * @summary Удалить рецепт
 */
export const deleteRecipesId = <TData = AxiosResponse<void>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.delete(`/recipes/${id}`, options);
};

/**
 * @summary Дублировать рецепт (для редактирования чужого)
 */
export const postRecipesIdDuplicate = <TData = AxiosResponse<Recipe>>(
  id: string,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/recipes/${id}/duplicate`, undefined, options);
};

/**
 * Создаёт meal из рецепта с указанным количеством порций
 * @summary Добавить рецепт в приём пищи
 */
export const postRecipesIdAddToMeal = <TData = AxiosResponse<Meal>>(
  id: string,
  addRecipeToMealRequest: AddRecipeToMealRequest,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(
    `/recipes/${id}/add-to-meal`,
    addRecipeToMealRequest,
    options,
  );
};

/**
 * @summary Поиск публичных рецептов
 */
export const getRecipesPublic = <TData = AxiosResponse<GetRecipesPublic200>>(
  params?: GetRecipesPublicParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/recipes/public`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * @summary Получить список планов
 */
export const getPlans = <TData = AxiosResponse<GetPlans200>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/plans`, options);
};

/**
 * @summary Применить план
 */
export const postPlansIdApply = <TData = AxiosResponse<PostPlansIdApply200>>(
  id: string,
  params?: PostPlansIdApplyParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.post(`/plans/${id}/apply`, undefined, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

/**
 * @summary Статистика за период
 */
export const getStats = <TData = AxiosResponse<StatsResponse>>(
  params: GetStatsParams,
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.get(`/stats`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export type PostAuthSignupResult = AxiosResponse<AuthResponse>;
export type PostAuthLoginResult = AxiosResponse<AuthResponse>;
export type PostAuthGoogleResult = AxiosResponse<AuthResponse>;
export type GetCalendarResult = AxiosResponse<GetCalendar200>;
export type GetDayDateResult = AxiosResponse<DayEntry>;
export type PostDayDateMealsResult = AxiosResponse<Meal>;
export type PutMealsIdResult = AxiosResponse<Meal>;
export type DeleteMealsIdResult = AxiosResponse<void>;
export type PostAiParseMealResult = AxiosResponse<AiParseMealResponse>;
export type GetProductsResult = AxiosResponse<GetProducts200>;
export type PostProductsResult = AxiosResponse<Product>;
export type GetProductsSearchResult = AxiosResponse<GetProductsSearch200>;
export type GetProductsIdResult = AxiosResponse<Product>;
export type PutProductsIdResult = AxiosResponse<Product>;
export type DeleteProductsIdResult = AxiosResponse<void>;
export type GetProductsBarcodeBarcodeResult = AxiosResponse<Product>;
export type GetRecipesResult = AxiosResponse<GetRecipes200>;
export type PostRecipesResult = AxiosResponse<Recipe>;
export type GetRecipesIdResult = AxiosResponse<Recipe>;
export type PutRecipesIdResult = AxiosResponse<Recipe>;
export type DeleteRecipesIdResult = AxiosResponse<void>;
export type PostRecipesIdDuplicateResult = AxiosResponse<Recipe>;
export type PostRecipesIdAddToMealResult = AxiosResponse<Meal>;
export type GetRecipesPublicResult = AxiosResponse<GetRecipesPublic200>;
export type GetPlansResult = AxiosResponse<GetPlans200>;
export type PostPlansIdApplyResult = AxiosResponse<PostPlansIdApply200>;
export type GetStatsResult = AxiosResponse<StatsResponse>;
